<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKylsgTQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKylsgTQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKylsgTQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKylsgTQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKylsgTQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'KylsgTQ',
    'container.build_id' => '9030eb7d',
    'container.build_time' => 1690353742,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKylsgTQ');
